---

- hosts: all
  connection: ssh
  gather_facts: yes
  become: yes

  tasks:

    - name: Install dependencies
      apt: 
        name: "{{ item }}"
        update_cache: true
        state: latest
      with_items:
        - acl
        - bash
        - build-essential
        - curl
        - gcc
        - make
        - openssl
        - postgresql
        - postgresql-contrib
        - python3
        - libpq-dev
        - libssl-dev
        - libssl-doc

    - name: Upgrade pip to latest
      pip:
        name: pip
        state: latest

    - name: Install python requirements
      pip:
        requirements: /vagrant/requirements.txt
